name: Hello World

on:
  push:
    branches : [ "main" ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: Set up jdk
        uses: actions/setup-java@v4
        with:
        # java-version: '19'
          java-version: '21'
          distribution: 'temurin'

      - name: Install dependency and run tests
        run: mvn test